import React, { ReactNode } from "react";
import Head from 'next/head'
import Link from "next/link";

interface ILayoutProps {
	children: ReactNode,
	name: string;
}
// agregar un navbar
const Layout = (props: ILayoutProps) => {
  const title = `JLGeogGUI: ${props.name}`;
	return (
		<React.Fragment>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className='h1'><Link href='/'>Brand</Link></h1>
			<main className='bg-light container'>{props.children}</main>

			<footer>

			</footer>
		</React.Fragment>
	)
}

export default Layout